# Generated by Django 5.2.6 on 2025-09-30 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_alter_blogpost_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, choices=[('Tehran', 'تهران'), ('isfahan', 'اصفهان')], max_length=63)),
                ('province', models.CharField(blank=True, max_length=63)),
                ('zip_code', models.CharField(blank=True, max_length=11)),
                ('hide_name', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.blogpost')),
            ],
        ),
    ]
