# Generated by Django 5.2.6 on 2025-09-30 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
