# Generated by Django 5.2.6 on 2025-10-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_comments_datetime_created_comments_datetime_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='city',
            field=models.CharField(blank=True, choices=[('Tehran', 'تهران'), ('isfahan', 'اصفهان')], max_length=63, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='hide_name',
            field=models.BooleanField(default=True, verbose_name='عدم نمایش نام'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.blogpost', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='province',
            field=models.CharField(blank=True, max_length=63, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='zip_code',
            field=models.CharField(blank=True, max_length=11, verbose_name='کد پستی'),
        ),
    ]
