# Generated by Django 5.2.6 on 2025-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_alter_comments_address_alter_comments_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='state',
            field=models.CharField(default='p', max_length=1, verbose_name='وضعیت کامنت'),
        ),
    ]
