# Generated by Django 5.2.6 on 2025-10-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_comments_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='state',
            field=models.CharField(choices=[('a', 'تایید شده'), ('r', 'رد شده'), ('p', 'در انتظار تایید')], default='p', max_length=1, verbose_name='وضعیت کامنت'),
        ),
    ]
