# Generated by Django 5.2.6 on 2025-10-12 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0010_remove_blogpost_likes_blogpostlikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogpostlikes',
            unique_together={('post', 'user')},
        ),
    ]
