# Generated by Django 5.2.6 on 2025-10-18 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(11, 'طول شماره موبایل حتما باید 11 رقم باشد'), django.core.validators.MaxLengthValidator(11, 'طول شماره موبایل حتما باید 11 رقم باشد')])),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'حداقل سفارش 1 عدد می باشد'), django.core.validators.MaxValueValidator(10, 'حداکثر سفارش 10 عدد می باشد')])),
            ],
        ),
    ]
