# Generated by Django 5.2.6 on 2025-10-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestioncritics',
            old_name='test',
            new_name='text',
        ),
    ]
