# Generated by Django 5.2.6 on 2025-10-20 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_test_suggestioncritics_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.food'),
        ),
    ]
